### ISSUE TITLE
[BUG]: Freshly cloned repo, password authentication failed for user "lago" thus cant create db properly

### ISSUE THREAD

**Issue by jameswong3388** [getlago/lago#306]
**Describe the bug**
A fresly cloned repo from official website, following the guide to generate the required env variables, changing postgresql and redis port. An error shown in the docker log, -> password authentication failed for user "lago" at the first launch 

**To Reproduce**
1. Modifiy `.env` and `docker-compose.yml`

`env`
```
# db
POSTGRES_PASSWORD="xxx"
POSTGRES_PORT=5433

# redis
REDIS_PORT=6380

# api
LAGO_API_HOSTNAME=<yourhostname>
LAGO_API_URL=https://<yourhostname>

# api worker
LAGO_RSA_PRIVATE_KEY="xxx"
SECRET_KEY_BASE="xxx"
LAGO_ENCRYPTION_PRIMARY_KEY="xxx"
LAGO_ENCRYPTION_DETERMINISTIC_KEY="xxx"
LAGO_ENCRYPTION_KEY_DERIVATION_SALT="xxx"

# front
LAGO_FRONT_URL=https://<yourhostname>
LAGO_HOSTNAME=<yourhostname>
```

`docker-compose.yml`
```
version: "3.8"

volumes:
  lago_postgres_data:
  lago_redis_data:
  lago_storage_data:

services:
  db:
    image: postgres:14.0-alpine
    container_name: lago-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lago}
      POSTGRES_USER: ${POSTGRES_USER:-lago}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      PGPORT: ${POSTGRES_PORT:-5432}
    volumes:
      - lago_postgres_data:/data/postgres
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    networks:
      - proxy

  redis:
    image: redis:6.2-alpine
    container_name: lago-redis
    restart: unless-stopped
    command: --port ${REDIS_PORT:-6379}
    volumes:
      - lago_redis_data:/data
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    networks:
      - proxy

  api:
    container_name: lago-api
    image: getlago/api:v0.53.1-beta
    restart: unless-stopped
    depends_on:
      - db
      - redis
    command: ["./scripts/start.sh"]
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    environment:
      - LAGO_API_URL=${LAGO_API_URL:-http://localhost:3000}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-lago}:${POSTGRES_PASSWORD:-changeme}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-lago}
      - REDIS_URL=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-your-secret-key-base-hex-64}
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=${LAGO_RAILS_STDOUT:-true}
      - SENTRY_DSN=${SENTRY_DSN}
      - LAGO_FRONT_URL=${LAGO_FRONT_URL:-http://localhost}
      - RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY} # Should be base64 encoded
      - LAGO_RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY} # Should be base64 encoded
      - LAGO_SIDEKIQ_WEB=${LAGO_SIDEKIQ_WEB}
      - ENCRYPTION_PRIMARY_KEY=${LAGO_ENCRYPTION_PRIMARY_KEY:-your-encrpytion-primary-key}
      - ENCRYPTION_DETERMINISTIC_KEY=${LAGO_ENCRYPTION_DETERMINISTIC_KEY:-your-encrpytion-deterministic-key}
      - ENCRYPTION_KEY_DERIVATION_SALT=${LAGO_ENCRYPTION_KEY_DERIVATION_SALT:-your-encrpytion-derivation-salt}
      - LAGO_USE_AWS_S3=${LAGO_USE_AWS_S3:-false}
      - LAGO_AWS_S3_ACCESS_KEY_ID=${LAGO_AWS_S3_ACCESS_KEY_ID:-azerty123456}
      - LAGO_AWS_S3_SECRET_ACCESS_KEY=${LAGO_AWS_S3_SECRET_ACCESS_KEY:-azerty123456}
      - LAGO_AWS_S3_REGION=${LAGO_AWS_S3_REGION:-us-east-1}
      - LAGO_AWS_S3_BUCKET=${LAGO_AWS_S3_BUCKET:-bucket}
      - LAGO_AWS_S3_ENDPOINT=${LAGO_AWS_S3_ENDPOINT}
      - LAGO_USE_GCS=${LAGO_USE_GCS:-false}
      - LAGO_GCS_PROJECT=${LAGO_GCS_PROJECT:-}
      - LAGO_GCS_BUCKET=${LAGO_GCS_BUCKET:-}
      - LAGO_PDF_URL=${LAGO_PDF_URL:-http://pdf:3000}
      - LAGO_REDIS_CACHE_URL=redis://${LAGO_REDIS_CACHE_HOST:-redis}:${LAGO_REDIS_CACHE_PORT:-6379}
      - LAGO_REDIS_CACHE_PASSWORD=${LAGO_REDIS_CACHE_PASSWORD}
      - LAGO_DISABLE_SEGMENT=${LAGO_DISABLE_SEGMENT}
      - LAGO_OAUTH_PROXY_URL=https://proxy.getlago.com
      - LAGO_LICENSE=${LAGO_LICENSE:-}
      # - SIDEKIQ_EVENTS=true
    volumes:
      - lago_storage_data:/app/storage
      # If using GCS, you need to put the credentials keyfile here
      #- gcs_keyfile.json:/app/gcs_keyfile.json
#    ports:
#      - ${API_PORT:-3000}:3000
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # Router
      - traefik.http.routers.lago-api.rule=Host(`${LAGO_API_HOSTNAME}`)
      - traefik.http.routers.lago-api.entrypoints=websecure
      # Services
      - traefik.http.routers.lago-api.service=lago-api-service
      - traefik.http.services.lago-api-service.loadbalancer.server.port=3000

  front:
    container_name: lago-front
    image: getlago/front:v0.53.2-beta
    restart: unless-stopped
    # Use this command if you want to use SSL with Let's Encrypt
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - api
    environment:
      - API_URL=${LAGO_API_URL:-http://localhost:3000}
      - APP_ENV=${APP_ENV:-production}
      - CODEGEN_API=${LAGO_API_URL:-http://localhost:3000}
      - LAGO_DISABLE_SIGNUP=${LAGO_DISABLE_SIGNUP:-false}
      - LAGO_OAUTH_PROXY_URL=https://proxy.getlago.com
      - SENTRY_DSN=${SENTRY_DSN_FRONT}
#    ports:
#      - ${FRONT_PORT:-80}:80
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # Router
      - traefik.http.routers.lago.rule=Host(`${LAGO_HOSTNAME}`)
      - traefik.http.routers.lago.entrypoints=websecure
      # Services
      - traefik.http.routers.lago.service=lago-service
      - traefik.http.services.lago-service.loadbalancer.server.port=80

  api-worker:
    container_name: lago-worker
    image: getlago/api:v0.53.2-beta
    restart: unless-stopped
    depends_on:
      - api
    command: ["./scripts/start.worker.sh"]
    healthcheck:
      test: ["CMD-SHELL", "bundle exec sidekiqmon | grep $(hostname) || exit 1"]
    environment:
      - LAGO_API_URL=${LAGO_API_URL:-http://localhost:3000}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-lago}:${POSTGRES_PASSWORD:-changeme}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-lago}
      - REDIS_URL=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-your-secret-key-base-hex-64}
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=${LAGO_RAILS_STDOUT:-true}
      - SENTRY_DSN=${SENTRY_DSN}
      - LAGO_RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY} # Should be base64 encoded
      - RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY} # Should be base64 encoded
      - ENCRYPTION_PRIMARY_KEY=${LAGO_ENCRYPTION_PRIMARY_KEY:-your-encrpytion-primary-key}
      - ENCRYPTION_DETERMINISTIC_KEY=${LAGO_ENCRYPTION_DETERMINISTIC_KEY:-your-encrpytion-deterministic-key}
      - ENCRYPTION_KEY_DERIVATION_SALT=${LAGO_ENCRYPTION_KEY_DERIVATION_SALT:-your-encrpytion-derivation-salt}
      - LAGO_FRONT_URL=${LAGO_FRONT_URL:-http://localhost}
      - LAGO_USE_AWS_S3=${LAGO_USE_AWS_S3:-false}
      - LAGO_AWS_S3_ACCESS_KEY_ID=${LAGO_AWS_S3_ACCESS_KEY_ID:-azerty123456}
      - LAGO_AWS_S3_SECRET_ACCESS_KEY=${LAGO_AWS_S3_SECRET_ACCESS_KEY:-azerty123456}
      - LAGO_AWS_S3_REGION=${LAGO_AWS_S3_REGION:-us-east-1}
      - LAGO_AWS_S3_BUCKET=${LAGO_AWS_S3_BUCKET:-bucket}
      - LAGO_AWS_S3_ENDPOINT=${LAGO_AWS_S3_ENDPOINT}
      - LAGO_USE_GCS=${LAGO_USE_GCS:-false}
      - LAGO_GCS_PROJECT=${LAGO_GCS_PROJECT:-}
      - LAGO_GCS_BUCKET=${LAGO_GCS_BUCKET:-}
      - LAGO_PDF_URL=${LAGO_PDF_URL:-http://pdf:3000}
      - LAGO_REDIS_CACHE_URL=redis://${LAGO_REDIS_CACHE_HOST:-redis}:${LAGO_REDIS_CACHE_PORT:-6379}
      - LAGO_REDIS_CACHE_PASSWORD=${LAGO_REDIS_CACHE_PASSWORD}
      - LAGO_DISABLE_SEGMENT=${LAGO_DISABLE_SEGMENT}
      # - SIDEKIQ_EVENTS=true
    volumes:
      - lago_storage_data:/app/storage
    networks:
      - proxy

  # You can uncomment this if you want to use a dedicated Sidekiq worker for the event ingestion.
  # It is recommendend if you have a high usage of events to not impact the other Sidekiq Jobs.
  #api-events-worker:
  #  container_name: lago-events-worker
  #  image: getlago/api:v0.53.2-beta
  #  restart: unless-stopped
  #  depends_on:
  #    - api
  #  command: ["./scripts/start.events.worker.sh"]
  #  environment:
  #    - LAGO_API_URL=${LAGO_API_URL:-http://localhost:3000}
  #    - DATABASE_URL=postgresql://${POSTGRES_USER:-lago}:${POSTGRES_PASSWORD:-changeme}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-lago}
  #    - REDIS_URL=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}
  #    - REDIS_PASSWORD=${REDIS_PASSWORD}
  #    - SECRET_KEY_BASE=${SECRET_KEY_BASE:-your-secret-key-base-hex-64}
  #    - RAILS_ENV=production
  #    - RAILS_LOG_TO_STDOUT=${LAGO_RAILS_STDOUT:-true}
  #    - SENTRY_DSN=${SENTRY_DSN}
  #    - LAGO_RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY} # Should be base64 encoded
  #    - RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY} # Should be base64 encoded
  #    - ENCRYPTION_PRIMARY_KEY=${LAGO_ENCRYPTION_PRIMARY_KEY:-your-encrpytion-primary-key}
  #    - ENCRYPTION_DETERMINISTIC_KEY=${LAGO_ENCRYPTION_DETERMINISTIC_KEY:-your-encrpytion-deterministic-key}
  #    - ENCRYPTION_KEY_DERIVATION_SALT=${LAGO_ENCRYPTION_KEY_DERIVATION_SALT:-your-encrpytion-derivation-salt}
  #    - LAGO_FRONT_URL=${LAGO_FRONT_URL:-http://localhost}
  #    - LAGO_USE_AWS_S3=${LAGO_USE_AWS_S3:-false}
  #    - LAGO_AWS_S3_ACCESS_KEY_ID=${LAGO_AWS_S3_ACCESS_KEY_ID:-azerty123456}
  #    - LAGO_AWS_S3_SECRET_ACCESS_KEY=${LAGO_AWS_S3_SECRET_ACCESS_KEY:-azerty123456}
  #    - LAGO_AWS_S3_REGION=${LAGO_AWS_S3_REGION:-us-east-1}
  #    - LAGO_AWS_S3_BUCKET=${LAGO_AWS_S3_BUCKET:-bucket}
  #    - LAGO_AWS_S3_ENDPOINT=${LAGO_AWS_S3_ENDPOINT}
  #    - LAGO_USE_GCS=${LAGO_USE_GCS:-false}
  #    - LAGO_GCS_PROJECT=${LAGO_GCS_PROJECT:-}
  #    - LAGO_GCS_BUCKET=${LAGO_GCS_BUCKET:-}
  #    - LAGO_PDF_URL=${LAGO_PDF_URL:-http://pdf:3000}
  #    - LAGO_REDIS_CACHE_URL=redis://${LAGO_REDIS_CACHE_HOST:-redis}:${LAGO_REDIS_CACHE_PORT:-6379}
  #    - LAGO_REDIS_CACHE_PASSWORD=${LAGO_REDIS_CACHE_PASSWORD}
  #    - LAGO_DISABLE_SEGMENT=${LAGO_DISABLE_SEGMENT}
  #    - SIDEKIQ_EVENTS=true

  api-clock:
    container_name: lago-clock
    image: getlago/api:v0.53.2-beta
    restart: unless-stopped
    depends_on:
      - api
    command: ["./scripts/start.clock.sh"]
    environment:
      - LAGO_API_URL=${LAGO_API_URL:-http://localhost:3000}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-lago}:${POSTGRES_PASSWORD:-changeme}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-lago}
      - REDIS_URL=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-your-secret-key-base-hex-64}
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=${LAGO_RAILS_STDOUT:-true}
      - SENTRY_DSN=${SENTRY_DSN}
      - LAGO_RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY} # Should be base64 encoded
      - RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY} # Should be base64 encoded
      - ENCRYPTION_PRIMARY_KEY=${LAGO_ENCRYPTION_PRIMARY_KEY:-your-encrpytion-primary-key}
      - ENCRYPTION_DETERMINISTIC_KEY=${LAGO_ENCRYPTION_DETERMINISTIC_KEY:-your-encrpytion-deterministic-key}
      - ENCRYPTION_KEY_DERIVATION_SALT=${LAGO_ENCRYPTION_KEY_DERIVATION_SALT:-your-encrpytion-derivation-salt}
    networks:
      - proxy

  pdf:
    image: getlago/lago-gotenberg:7
    networks:
      - proxy

networks:
  proxy:
    external: true
```

2. docker-compose up -d (as described in the documentation and all steps before)
3. Trying to signup.

**Expected behavior**
Signup should work

**Screenshots**
**Client**
<img width="1466" alt="Screenshot 2023-12-27 at 5 27 48 PM" src="https://github.com/getlago/lago/assets/87692325/e5f15557-b0f4-4fd5-a163-86cf573d4b87">

**lago-db logs**
<img width="1116" alt="Screenshot 2023-12-27 at 5 28 47 PM" src="https://github.com/getlago/lago/assets/87692325/75d85464-cdcf-449a-9405-70ce25bfa9e2">

**lago-api logs**
<img width="1130" alt="Screenshot 2023-12-27 at 5 29 41 PM" src="https://github.com/getlago/lago/assets/87692325/9078104e-499d-476f-81e5-3e5427038aa6">

**lago-worker logs**
<img width="1128" alt="Screenshot 2023-12-27 at 5 30 32 PM" src="https://github.com/getlago/lago/assets/87692325/ab777e84-390d-4110-a166-e966a9473493">

**Support**
 - Ubuntu
 - Safari
