### ISSUE TITLE
[BUG]: Invoice pdf generation not working with Docker

### ISSUE THREAD

**Issue by frohrlich** [getlago/lago#535]
**Describe the bug**
When trying to download an invoice, nothing happens and I see a 500 error in the console.

**To Reproduce**
1. Create a customer
2. Create a plan
3. Assign plan to customer
4. Terminate plan
5. An invoice should be generated, click on the invoice tab and "download invoice"

**Expected behavior**
Invoice should be generated and downloaded.

**Screenshots**
![Image](https://github.com/user-attachments/assets/a7898661-0663-4893-a1e3-126e8e14cdeb)

**Support**
I use the Lago Docker one-click command (v1.28.1) in my own docker-compose file, like this:
```
services:
  lago:
    image: getlago/lago:v1.28.1
    ports:
      - 80:80
      - 3000:3000
    environment:
      LAGO_DISABLE_SEGMENT: true
```

**Additional context**
I see nothing in the logs.
