### ISSUE TITLE
[BUG]: PDF generation not working in one-click docker image

### ISSUE THREAD

**Issue by frohrlich** [getlago/lago#541]
The invoice PDF generation still doesn't work with the one-click docker image. I know you had provided a fix for this but it seems to fail at container startup, as I get this message:
```
WARN: Docker socket is not mounted. Skipping PDF service.
```

When I try to generate an invoice pdf later it indeed fails with a 500 internal error from the API.

I'm using docker one-click image version 1.29.0, with my own docker compose file, like this:
```
services:
  lago:
    image: getlago/lago:v1.29.0
    ports:
      - 80:80
      - 3000:3000
    environment:
      LAGO_DISABLE_SEGMENT: true
```

**Comment by jdenquin** [comment]
Hey @frohrlich did you pass the volume with your docker socket when you start the image?

**Comment by jdenquin** [comment]
sorry I didn't see your docker-compose configuration, can you try with 

```
services:
  lago:
    image: getlago/lago:v1.29.0
    ports:
      - 80:80
      - 3000:3000
    environment:
      LAGO_DISABLE_SEGMENT: true
    volume:
        - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by geoextra** [comment]
This issue also affects the ["quickstart" docker command from the documentation](https://getlago.com/docs/guide/self-hosted/docker):
`docker run -d --name lago -p 80:80 -p 3000:3000 getlago/lago:latest`

**Comment by jdenquin** [comment]
@geoextra yes this is the intended behavior, if you want to have the PDF service running, you have to pass your Docker socker
`docker run -d --name lago -v /var/run/docker.sock:/var/run/docker.sock -p 80:80 -p 3000:3000 getlago/lago:latest`

**Comment by frohrlich** [comment]
I passed the docker socket as you said, and the startup error message disappeared, but now I still have a 500 error when trying to generate the pdf.
I have this in the logs:
```
lago-1  | 08:31:38 web.1    | {"method":"POST","path":"/graphql","format":"*/*","controller":"GraphqlController","action":"execute","status":500,"allocations":121738,"duration":96.3,"view":0.0,"db":14.28,"level":"error","ddsource":"ruby","params":{"operationName":"downloadInvoiceItem","variables":{"input":{"id":"86154d45-6d79-4c96-8fc6-46f92cd16ce5"}},"query":"mutation downloadInvoiceItem($input: DownloadInvoiceInput!) {\n  downloadInvoice(input: $input) {\n    id\n    fileUrl\n    __typename\n  }\n}"},"organization_id":"fdd717db-c5c1-4d9e-acf8-7e6884dd557f","trace_id":"00000000000000000000000000000000","span_id":"0000000000000000"}
lago-1  | 08:31:38 web.1    |   
lago-1  | 08:31:38 web.1    | Errno::ECONNREFUSED (Failed to open TCP connection to host.docker.internal:3001 (Connection refused - connect(2) for "host.docker.internal" port 3001))
lago-1  | 08:31:38 web.1    | Caused by: Errno::ECONNREFUSED (Connection refused - connect(2) for "host.docker.internal" port 3001)
lago-1  | 08:31:38 web.1    | 
lago-1  | 08:31:38 web.1    | Information for: Errno::ECONNREFUSED (Failed to open TCP connection to host.docker.internal:3001 (Connection refused - connect(2) for "host.docker.internal" port 3001)):
lago-1  | 08:31:38 web.1    |   
lago-1  | 08:31:38 web.1    | lib/lago_http_client/lago_http_client/client.rb:74:in 'LagoHttpClient::Client#post_multipart_file'
lago-1  | 08:31:38 web.1    | app/services/utils/pdf_generator.rb:38:in 'Utils::PdfGenerator#render_pdf'
lago-1  | 08:31:38 web.1    | app/services/utils/pdf_generator.rb:15:in 'Utils::PdfGenerator#call'
lago-1  | 08:31:38 web.1    | app/services/invoices/generate_pdf_service.rb:36:in 'block in Invoices::GeneratePdfService#generate_pdf'
lago-1  | 08:31:38 web.1    | app/services/invoices/generate_pdf_service.rb:34:in 'Invoices::GeneratePdfService#generate_pdf'
lago-1  | 08:31:38 web.1    | app/services/invoices/generate_pdf_service.rb:17:in 'Invoices::GeneratePdfService#call'
lago-1  | 08:31:38 web.1    | app/services/base_service.rb:231:in 'block in BaseService.call'
lago-1  | 08:31:38 web.1    | app/services/base_service.rb:230:in 'BaseService.call'
lago-1  | 08:31:38 web.1    | app/graphql/mutations/invoices/download.rb:20:in 'Mutations::Invoices::Download#resolve'
lago-1  | 08:31:38 web.1    | 
lago-1  | 08:31:38 web.1    | Information for cause: Errno::ECONNREFUSED (Connection refused - connect(2) for "host.docker.internal" port 3001):
lago-1  | 08:31:38 web.1    |   
lago-1  | 08:31:38 web.1    | lib/lago_http_client/lago_http_client/client.rb:74:in 'LagoHttpClient::Client#post_multipart_file'
lago-1  | 08:31:38 web.1    | app/services/utils/pdf_generator.rb:38:in 'Utils::PdfGenerator#render_pdf'
lago-1  | 08:31:38 web.1    | app/services/utils/pdf_generator.rb:15:in 'Utils::PdfGenerator#call'
lago-1  | 08:31:38 web.1    | app/services/invoices/generate_pdf_service.rb:36:in 'block in Invoices::GeneratePdfService#generate_pdf'
lago-1  | 08:31:38 web.1    | app/services/invoices/generate_pdf_service.rb:34:in 'Invoices::GeneratePdfService#generate_pdf'
lago-1  | 08:31:38 web.1    | app/services/invoices/generate_pdf_service.rb:17:in 'Invoices::GeneratePdfService#call'
lago-1  | 08:31:38 web.1    | app/services/base_service.rb:231:in 'block in BaseService.call'
lago-1  | 08:31:38 web.1    | app/services/base_service.rb:230:in 'BaseService.call'
lago-1  | 08:31:38 web.1    | app/graphql/mutations/invoices/download.rb:20:in 'Mutations::Invoices::Download#resolve'
```

**Comment by jdenquin** [comment]
@frohrlich can you check that your PDF service is running on port 3001 in docker?

**Comment by frohrlich** [comment]
Ok I figured it out, the lago container couldn't connect to the pdf container because I missed a piece of configuration (specific to Linux apparently) to connect to localhost from docker. I added these lines in my docker-compose file and now pdf generation finally works:
```
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
For those using docker run you should add this flag:
```
--add-host=host.docker.internal:host-gateway
```

My complete docker-compose.yml file:
```
services:
  lago:
    image: getlago/lago:v1.29.0
    ports:
      - 80:80
      - 3000:3000
    environment:
      LAGO_DISABLE_SEGMENT: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

Thank you @jdenquin
